import type { Metadata } from "next"
import { Inter, Zeyada } from "next/font/google"
import "./globals.css"
import Pattern from "@/illustrations/Pattern"
import SideInfo from "@/components/SideInfo"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-white overflow-x-hidden"}>
        <div className="relative z-10">
          {children}
          <SideInfo />
        </div>
        <div className="md:block hidden fixed inset-0 pointer-events-none">
          <Pattern className="absolute inset-0 opacity-50" />
          <div className="border-[256px] border-white inset-0 absolute blur-3xl" />
        </div>
      </body>
    </html>
  )
}
